# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do

  desc "Upload build to TestFlight"
  lane :beta do
    build_app(
      scheme: "YourSchemeName",
      export_method: "app-store"
    )

    upload_to_testflight(
      beta_app_description: "Beta build",
      beta_app_feedback_email: "you@email.com",
      submit_for_beta_review: true,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Release to App Store"
  lane :release do
    build_app(
      scheme: "YourSchemeName",
      export_method: "app-store"
    )

    upload_to_app_store(
      submit_for_review: false,
      automatic_release: false
    )
  end
end
# platform :ios do
#   desc "Push a new release build to the App Store"
#   lane :release do
#     increment_build_number(xcodeproj: "netflix-clone-github.xcodeproj")
#     build_app(scheme: "netflix-clone-github")
#     upload_to_app_store
#   end
# end
